# -*- coding: utf-8 -*-
"""類似度検索.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A4VZeb2LcbXsQ06Rq50DN62MgBBsqaWL
"""

!pip install fugashi
!pip install unidic-lite

from transformers import AutoTokenizer, AutoModel
import torch
import torch.nn.functional as F

# 日本語BERTモデル（Cl-tohoku）
model_name = "cl-tohoku/bert-base-japanese"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModel.from_pretrained(model_name)

# テキスト（職種名）をベクトルに変換する関数
def get_embedding(text):
    inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True)
    with torch.no_grad():
        outputs = model(**inputs)
    cls_embedding = outputs.last_hidden_state[:, 0, :]
    return cls_embedding.squeeze()

# 類似度の計算
def cosine_similarity(vec1, vec2):
    return F.cosine_similarity(vec1.unsqueeze(0), vec2.unsqueeze(0)).item()


job1 = "介護"
job2 = "極悪非道"

vec1 = get_embedding(job1)
vec2 = get_embedding(job2)
# 職種の類似度を求める
similarity = cosine_similarity(vec1, vec2)

print(f"類似度: {similarity:.3f}")  # 0〜1の範囲

"""# ClTohokuよりも精度が高い"""

from transformers import AutoTokenizer, AutoModel
import torch
import torch.nn.functional as F

model_name = "cl-tohoku/bert-large-japanese-v2"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModel.from_pretrained(model_name)

# 平均プーリングを使うことでより良い結果が得られる場合がある
def get_embedding(text):
    inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True)
    with torch.no_grad():
        outputs = model(**inputs)

    # 全トークンの平均を取る
    token_embeddings = outputs.last_hidden_state
    attention_mask = inputs['attention_mask']
    mask_expanded = attention_mask.unsqueeze(-1).expand(token_embeddings.size()).float()

    sum_embeddings = torch.sum(token_embeddings * mask_expanded, 1)
    sum_mask = mask_expanded.sum(1)
    mean_pooled = sum_embeddings / sum_mask

    return mean_pooled.squeeze()

# 例：職種の類似度を求める
# 看護師、ナースよりも介護士、ナースのほうが低い。実感とも合う
job1 = "看護師"
job2 = "ナース"


vec1 = get_embedding(job1)
vec2 = get_embedding(job2)
similarity = cosine_similarity(vec1, vec2)

print(f"類似度: {similarity:.3f}")  # → 例えば 0.82 とか

"""### SentenceTransformers
候補3
"""

from sentence_transformers import SentenceTransformer, util

# 日本語対応モデル
# 全くだめ。→ 看護師ナースよりも、介護士とナースのほうが近い
model = SentenceTransformer('paraphrase-multilingual-mpnet-base-v2')
# または
# model = SentenceTransformer('sonoisa/sentence-bert-base-ja-mean-tokens-v2')

job1 = "介護士"
job2 = "ナース"

embedding1 = model.encode(job1)
embedding2 = model.encode(job2)

similarity = util.cos_sim(embedding1, embedding2)[0][0].item()
print(f"類似度: {similarity:.3f}")

# Google Colab用の評価コード

# 必要なライブラリのインストール
!pip install -q transformers torch sentence-transformers

import torch
import numpy as np
from transformers import AutoTokenizer, AutoModel
from sentence_transformers import SentenceTransformer, util
import torch.nn.functional as F
from sklearn.metrics import ndcg_score
from scipy.stats import spearmanr, kendalltau
import datetime

# 1. モデル定義
class JobSimilarityEvaluator:
    def __init__(self):
        # 各モデルの初期化
        print("モデルを初期化中...")

        # BERT (cl-tohoku)
        self.bert_name = "cl-tohoku/bert-base-japanese"
        self.bert_tokenizer = AutoTokenizer.from_pretrained(self.bert_name)
        self.bert_model = AutoModel.from_pretrained(self.bert_name)

        # BERT-large
        self.bert_large_name = "cl-tohoku/bert-large-japanese-v2"
        self.bert_large_tokenizer = AutoTokenizer.from_pretrained(self.bert_large_name)
        self.bert_large_model = AutoModel.from_pretrained(self.bert_large_name)

        # Sentence Transformers
        self.st_model = SentenceTransformer('paraphrase-multilingual-mpnet-base-v2')
        self.st_model_jp = SentenceTransformer('sonoisa/sentence-bert-base-ja-mean-tokens-v2')

        # デバイスの設定
        self.device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
        self.bert_model.to(self.device)
        self.bert_large_model.to(self.device)

        print("モデルの初期化が完了しました")

    def get_bert_embedding(self, text, large=False):
        """BERTの埋め込みを取得"""
        if large:
            tokenizer = self.bert_large_tokenizer
            model = self.bert_large_model
        else:
            tokenizer = self.bert_tokenizer
            model = self.bert_model

        inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True).to(self.device)
        with torch.no_grad():
            outputs = model(**inputs)

        # CLSトークンの埋め込みを使用
        cls_embedding = outputs.last_hidden_state[:, 0, :]
        return cls_embedding.cpu().squeeze().numpy()

    def get_bert_mean_pooling(self, text, large=False):
        """BERTの平均プーリング埋め込みを取得"""
        if large:
            tokenizer = self.bert_large_tokenizer
            model = self.bert_large_model
        else:
            tokenizer = self.bert_tokenizer
            model = self.bert_model

        inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True).to(self.device)
        with torch.no_grad():
            outputs = model(**inputs)

        # 平均プーリング
        token_embeddings = outputs.last_hidden_state
        attention_mask = inputs['attention_mask']
        mask_expanded = attention_mask.unsqueeze(-1).expand(token_embeddings.size()).float()

        sum_embeddings = torch.sum(token_embeddings * mask_expanded, 1)
        sum_mask = mask_expanded.sum(1)
        mean_pooled = sum_embeddings / sum_mask

        return mean_pooled.cpu().squeeze().numpy()

    def get_sentence_transformer_embedding(self, text, jp=False):
        """Sentence Transformerの埋め込みを取得"""
        if jp:
            return self.st_model_jp.encode(text)
        else:
            return self.st_model.encode(text)

    def cosine_similarity(self, vec1, vec2):
        """コサイン類似度を計算"""
        return np.dot(vec1, vec2) / (np.linalg.norm(vec1) * np.linalg.norm(vec2))

# 2. 評価データセットの定義
evaluation_dataset = [
    {
        "anchor": "レジ打ち",
        "similar": ["レジ係", "キャッシャー", "精算係", "会計担当"],
        "different": ["プログラマー", "医師", "建築士", "弁護士"]
    },
    {
        "anchor": "プログラマー",
        "similar": ["ソフトウェアエンジニア", "開発者", "コーダー", "システムエンジニア"],
        "different": ["販売員", "料理人", "運転手", "警備員"]
    },
    {
        "anchor": "営業職",
        "similar": ["セールス", "営業担当", "販売推進", "営業マネージャー"],
        "different": ["経理", "研究員", "保育士", "清掃員"]
    },
    {
        "anchor": "看護師",
        "similar": ["ナース", "看護職員", "病棟看護師", "臨床看護師"],
        "different": ["プログラマー", "営業", "デザイナー", "建設作業員"]
    },
    {
        "anchor": "データサイエンティスト",
        "similar": ["データアナリスト", "機械学習エンジニア", "AIエンジニア", "統計解析担当"],
        "different": ["事務員", "警備員", "配送ドライバー", "調理師"]
    }
]

# 3. 評価の実行
def run_evaluation():
    evaluator = JobSimilarityEvaluator()

    # 評価するモデルの定義
    models = {
        "BERT (CLS)": lambda text: evaluator.get_bert_embedding(text, large=False),
        "BERT (Mean Pooling)": lambda text: evaluator.get_bert_mean_pooling(text, large=False),
        "BERT-large (CLS)": lambda text: evaluator.get_bert_embedding(text, large=True),
        "BERT-large (Mean Pooling)": lambda text: evaluator.get_bert_mean_pooling(text, large=True),
        "Sentence-BERT (Multilingual)": lambda text: evaluator.get_sentence_transformer_embedding(text, jp=False),
        "Sentence-BERT (Japanese)": lambda text: evaluator.get_sentence_transformer_embedding(text, jp=True),
    }

    results = {}

    # 各モデルの評価
    for model_name, embedding_func in models.items():
        print(f"\n=== {model_name} の評価 ===")
        model_results = []

        # 各評価データに対して
        for data in evaluation_dataset:
            anchor = data["anchor"]
            similar_jobs = data["similar"]
            different_jobs = data["different"]

            # アンカーの埋め込みを取得
            anchor_embedding = embedding_func(anchor)

            # 類似・非類似の職種の類似度を計算
            similar_scores = []
            for job in similar_jobs:
                job_embedding = embedding_func(job)
                similarity = evaluator.cosine_similarity(anchor_embedding, job_embedding)
                similar_scores.append(similarity)

            different_scores = []
            for job in different_jobs:
                job_embedding = embedding_func(job)
                similarity = evaluator.cosine_similarity(anchor_embedding, job_embedding)
                different_scores.append(similarity)

            # 平均スコアの計算
            avg_similar = np.mean(similar_scores)
            avg_different = np.mean(different_scores)
            separation = avg_similar - avg_different

            model_results.append({
                "anchor": anchor,
                "avg_similar": avg_similar,
                "avg_different": avg_different,
                "separation": separation,
                "similar_scores": similar_scores,
                "different_scores": different_scores
            })

        results[model_name] = model_results

    # 4. 結果の出力
    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    output_file = f"job_similarity_evaluation_{timestamp}.txt"

    with open(output_file, "w", encoding="utf-8") as f:
        f.write("職種類似度モデルの評価結果\n")
        f.write("=" * 50 + "\n\n")
        f.write(f"評価日時: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n")

        # モデルごとの集計結果
        f.write("【モデル比較サマリー】\n")
        f.write("-" * 30 + "\n")
        for model_name, model_results in results.items():
            avg_separation = np.mean([r["separation"] for r in model_results])
            f.write(f"{model_name}:\n")
            f.write(f"  平均分離度: {avg_separation:.3f}\n")
        f.write("\n")

        # 詳細な結果
        f.write("【詳細結果】\n")
        f.write("=" * 50 + "\n\n")

        for model_name, model_results in results.items():
            f.write(f"モデル: {model_name}\n")
            f.write("-" * 30 + "\n")

            for result in model_results:
                f.write(f"アンカー職種: {result['anchor']}\n")
                f.write(f"  類似職種の平均スコア: {result['avg_similar']:.3f}\n")
                f.write(f"  非類似職種の平均スコア: {result['avg_different']:.3f}\n")
                f.write(f"  分離度: {result['separation']:.3f}\n")

                f.write("  類似職種の詳細:\n")
                for i, (job, score) in enumerate(zip(evaluation_dataset[model_results.index(result)]["similar"], result['similar_scores'])):
                    f.write(f"    - {job}: {score:.3f}\n")

                f.write("  非類似職種の詳細:\n")
                for i, (job, score) in enumerate(zip(evaluation_dataset[model_results.index(result)]["different"], result['different_scores'])):
                    f.write(f"    - {job}: {score:.3f}\n")
                f.write("\n")

            f.write("\n" + "=" * 50 + "\n\n")

    print(f"評価結果を {output_file} に保存しました")

    # Google Colabでファイルをダウンロード
    from google.colab import files
    files.download(output_file)

# 実行
if __name__ == "__main__":
    run_evaluation()