# -*- coding: utf-8 -*-
"""類似度検索2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vUpGjt7BRXxBr_XMRBVkwir8V2zCREJP
"""

!pip install fugashi
!pip install unidic-lite

# Google Colab用の職務経歴書と求人スキル類似度評価コード

# 必要なライブラリのインストール
!pip install -q transformers torch sentence-transformers japanize-matplotlib

import torch
import numpy as np
import matplotlib.pyplot as plt
import japanize_matplotlib
from transformers import AutoTokenizer, AutoModel
from sentence_transformers import SentenceTransformer, util
import torch.nn.functional as F
from sklearn.metrics import ndcg_score
from scipy.stats import spearmanr, kendalltau
import datetime
import pandas as pd
import seaborn as sns

# 1. モデル定義
class ResumeJobSimilarityEvaluator:
    def __init__(self):
        # 各モデルの初期化
        print("モデルを初期化中...")

        # BERT (cl-tohoku)
        self.bert_name = "cl-tohoku/bert-base-japanese"
        self.bert_tokenizer = AutoTokenizer.from_pretrained(self.bert_name)
        self.bert_model = AutoModel.from_pretrained(self.bert_name)

        # BERT-large
        self.bert_large_name = "cl-tohoku/bert-large-japanese-v2"
        self.bert_large_tokenizer = AutoTokenizer.from_pretrained(self.bert_large_name)
        self.bert_large_model = AutoModel.from_pretrained(self.bert_large_name)

        # Sentence Transformers
        self.st_model = SentenceTransformer('paraphrase-multilingual-mpnet-base-v2')
        self.st_model_jp = SentenceTransformer('sonoisa/sentence-bert-base-ja-mean-tokens-v2')

        # 新たに追加するモデル
        self.luke_jp_name = "studio-ousia/luke-japanese-base-lite"
        self.luke_jp_tokenizer = AutoTokenizer.from_pretrained(self.luke_jp_name)
        self.luke_jp_model = AutoModel.from_pretrained(self.luke_jp_name)

        # より最新のSentence Transformersモデル
        self.st_model_jp_new = SentenceTransformer('sonoisa/sentence-luke-japanese-base-lite')

        # デバイスの設定
        self.device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
        self.bert_model.to(self.device)
        self.bert_large_model.to(self.device)
        self.luke_jp_model.to(self.device)

        print(f"モデルの初期化が完了しました。使用デバイス: {self.device}")

    def get_bert_embedding(self, text, large=False):
        """BERTの埋め込みを取得"""
        if large:
            tokenizer = self.bert_large_tokenizer
            model = self.bert_large_model
        else:
            tokenizer = self.bert_tokenizer
            model = self.bert_model

        inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True, max_length=512).to(self.device)
        with torch.no_grad():
            outputs = model(**inputs)

        # CLSトークンの埋め込みを使用
        cls_embedding = outputs.last_hidden_state[:, 0, :]
        return cls_embedding.cpu().squeeze().numpy()

    def get_bert_mean_pooling(self, text, large=False):
        """BERTの平均プーリング埋め込みを取得"""
        if large:
            tokenizer = self.bert_large_tokenizer
            model = self.bert_large_model
        else:
            tokenizer = self.bert_tokenizer
            model = self.bert_model

        inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True, max_length=512).to(self.device)
        with torch.no_grad():
            outputs = model(**inputs)

        # 平均プーリング
        token_embeddings = outputs.last_hidden_state
        attention_mask = inputs['attention_mask']
        mask_expanded = attention_mask.unsqueeze(-1).expand(token_embeddings.size()).float()

        sum_embeddings = torch.sum(token_embeddings * mask_expanded, 1)
        sum_mask = mask_expanded.sum(1)
        mean_pooled = sum_embeddings / sum_mask

        return mean_pooled.cpu().squeeze().numpy()

    def get_luke_embedding(self, text):
        """LUKE日本語モデルの埋め込みを取得"""
        tokenizer = self.luke_jp_tokenizer
        model = self.luke_jp_model

        inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True, max_length=512).to(self.device)
        with torch.no_grad():
            outputs = model(**inputs)

        # CLSトークンの埋め込みを使用
        cls_embedding = outputs.last_hidden_state[:, 0, :]
        return cls_embedding.cpu().squeeze().numpy()

    def get_sentence_transformer_embedding(self, text, model_type="multilingual"):
        """Sentence Transformerの埋め込みを取得"""
        if model_type == "japanese":
            return self.st_model_jp.encode(text)
        elif model_type == "japanese_luke":
            return self.st_model_jp_new.encode(text)
        else:  # multilingual
            return self.st_model.encode(text)

    def cosine_similarity(self, vec1, vec2):
        """コサイン類似度を計算"""
        if isinstance(vec1, list):
            vec1 = np.array(vec1)
        if isinstance(vec2, list):
            vec2 = np.array(vec2)
        return np.dot(vec1, vec2) / (np.linalg.norm(vec1) * np.linalg.norm(vec2))

    def get_resume_job_similarity(self, resume_text, job_description, embedding_func):
        """職務経歴と求人の類似度を計算"""
        resume_embedding = embedding_func(resume_text)
        job_embedding = embedding_func(job_description)
        return self.cosine_similarity(resume_embedding, job_embedding)

    def get_weighted_resume_job_similarity(self, resume_text, job_description, embedding_func,
                                          important_keywords=None, keyword_weight=1.5):
        """重要キーワードに重みを付けた類似度計算"""
        # 基本の埋め込みを取得
        resume_embedding = embedding_func(resume_text)
        job_embedding = embedding_func(job_description)

        # 基本の類似度
        base_similarity = self.cosine_similarity(resume_embedding, job_embedding)

        # 重要キーワードがない場合は基本の類似度を返す
        if not important_keywords:
            return base_similarity

        # キーワードの出現回数をカウント
        resume_keyword_count = sum(1 for keyword in important_keywords if keyword.lower() in resume_text.lower())
        job_keyword_count = sum(1 for keyword in important_keywords if keyword.lower() in job_description.lower())

        # 両方のテキストに共通して出現するキーワードの数
        common_keywords = sum(1 for keyword in important_keywords
                             if keyword.lower() in resume_text.lower() and keyword.lower() in job_description.lower())

        # キーワード一致度の計算（0〜1の範囲）
        if len(important_keywords) > 0:
            keyword_match_ratio = common_keywords / len(important_keywords)
        else:
            keyword_match_ratio = 0

        # 重み付け類似度の計算
        weighted_similarity = base_similarity * (1 - keyword_weight) + keyword_match_ratio * keyword_weight

        return weighted_similarity

# 2. 評価データセットの定義
evaluation_dataset = [
    {
        "resume": """
        【職務経歴】
        2018年4月～現在: 株式会社テックソリューション
        ・Pythonを使用したWebアプリケーション開発
        ・機械学習モデルの実装と最適化
        ・データ分析と可視化
        ・チームリーダーとしてプロジェクト管理

        2015年4月～2018年3月: 株式会社ITサービス
        ・Javaを使用したエンタープライズアプリケーション開発
        ・データベース設計と最適化
        ・クライアントとの要件定義

        【スキル】
        言語: Python, Java, JavaScript, SQL
        フレームワーク: Django, Flask, Spring, React
        ツール: Git, Docker, AWS, TensorFlow
        """,
        "matching_jobs": [
            """
            【募集職種】データサイエンティスト
            【必要スキル】
            ・Pythonによるデータ分析経験3年以上
            ・機械学習モデルの実装経験
            ・データ可視化ツールの使用経験
            ・TensorFlowまたはPyTorchの使用経験
            【歓迎スキル】
            ・チームリーダー経験
            ・クラウド環境（AWS, GCP等）での実務経験
            """,
            """
            【募集職種】バックエンドエンジニア
            【必要スキル】
            ・PythonまたはJavaでのWeb開発経験
            ・RESTful APIの設計と実装経験
            ・SQLデータベースの知識
            ・Gitによるバージョン管理経験
            【歓迎スキル】
            ・マイクロサービスアーキテクチャの経験
            ・コンテナ技術（Docker, Kubernetes）の知識
            """
        ],
        "non_matching_jobs": [
            """
            【募集職種】フロントエンドエンジニア（Vue.js専門）
            【必要スキル】
            ・Vue.jsを使用したSPA開発経験3年以上
            ・TypeScriptの実務経験
            ・CSSプリプロセッサ（SASS, LESS）の使用経験
            ・Vuexを用いた状態管理の経験
            【歓迎スキル】
            ・デザインシステム構築経験
            ・Webパフォーマンスチューニングスキル
            """,
            """
            【募集職種】インフラエンジニア
            【必要スキル】
            ・Linux/UNIXサーバー管理経験
            ・ネットワーク設計と構築経験
            ・セキュリティ対策の実装経験
            ・シェルスクリプトによる自動化経験
            【歓迎スキル】
            ・クラウドインフラ（AWS, Azure）の構築経験
            ・監視ツール（Prometheus, Grafana等）の導入経験
            """
        ]
    },
    {
        "resume": """
        【職務経歴】
        2019年7月～現在: 株式会社デザインクリエイト
        ・Webサイトのデザインと実装
        ・ユーザーインターフェースの設計
        ・クライアントとの打ち合わせとデザイン提案
        ・HTML/CSS/JavaScriptによるフロントエンド開発

        2016年4月～2019年6月: 株式会社クリエイティブワークス
        ・バナー広告やLP制作
        ・企業ブランディングのデザイン
        ・Adobe製品を使用したグラフィックデザイン

        【スキル】
        デザインツール: Adobe Photoshop, Illustrator, XD, Figma
        言語: HTML, CSS, JavaScript
        フレームワーク: Bootstrap, SASS
        その他: レスポンシブデザイン, UI/UXデザイン原則
        """,
        "matching_jobs": [
            """
            【募集職種】UIデザイナー
            【必要スキル】
            ・WebデザインとUIデザインの経験3年以上
            ・Adobe XDまたはFigmaの使用経験
            ・レスポンシブデザインの実装経験
            ・ユーザー中心設計の知識
            【歓迎スキル】
            ・HTML/CSSの基本的な知識
            ・プロトタイピングツールの経験
            """,
            """
            【募集職種】フロントエンドデザイナー
            【必要スキル】
            ・HTML/CSS/JavaScriptの実装経験
            ・デザインツール（Photoshop, XD等）の使用経験
            ・レスポンシブウェブデザインの知識
            ・クロスブラウザ対応の経験
            【歓迎スキル】
            ・SASSやLESSなどのCSSプリプロセッサの経験
            ・Gitの基本的な使用経験
            """
        ],
        "non_matching_jobs": [
            """
            【募集職種】バックエンドエンジニア
            【必要スキル】
            ・Java, Pythonなどのサーバーサイド言語の経験
            ・RDBMSの設計と実装経験
            ・RESTful APIの設計と実装
            ・マイクロサービスアーキテクチャの知識
            【歓迎スキル】
            ・Dockerなどのコンテナ技術の経験
            ・CI/CDパイプラインの構築経験
            """,
            """
            【募集職種】データアナリスト
            【必要スキル】
            ・SQLによるデータ抽出と分析経験
            ・Rまたはpythonでの統計分析経験
            ・データ可視化ツールの使用経験
            ・ビジネス課題を理解し分析する能力
            【歓迎スキル】
            ・統計学または数学の学位
            ・BIツール（Tableau, PowerBIなど）の使用経験
            """
        ]
    },
    {
        "resume": """
        【職務経歴】
        2020年4月～現在: 株式会社マーケティングプラス
        ・デジタルマーケティング戦略の策定と実行
        ・SNS広告の運用と分析
        ・コンテンツマーケティングの企画と実施
        ・顧客データ分析とインサイト抽出

        2017年4月～2020年3月: 株式会社アドバタイズ
        ・Web広告の運用（Google広告、Yahoo!広告）
        ・広告のA/Bテストと効果測定
        ・クライアントへの提案と報告

        【スキル】
        ツール: Google Analytics, Google Tag Manager, Google広告, Facebook広告
        分析: データ分析, A/Bテスト, コンバージョン最適化
        その他: コンテンツ制作, SEO対策, マーケティング戦略立案
        """,
        "matching_jobs": [
            """
            【募集職種】Webマーケター
            【必要スキル】
            ・Web広告運用経験（Google広告、SNS広告）
            ・Google Analyticsによるデータ分析経験
            ・マーケティング戦略の策定経験
            ・コンテンツマーケティングの知識
            【歓迎スキル】
            ・SEO対策の実施経験
            ・CRMツールの使用経験
            """,
            """
            【募集職種】デジタルマーケティングマネージャー
            【必要スキル】
            ・デジタルマーケティング経験3年以上
            ・広告運用とKPI管理経験
            ・データ分析に基づく意思決定能力
            ・チームマネジメント経験
            【歓迎スキル】
            ・マーケティングオートメーションツールの経験
            ・予算管理と費用対効果分析経験
            """
        ],
        "non_matching_jobs": [
            """
            【募集職種】ソフトウェアエンジニア
            【必要スキル】
            ・Java, C#などの言語でのアプリケーション開発経験
            ・オブジェクト指向プログラミングの理解
            ・データベース設計と実装経験
            ・アジャイル開発手法の経験
            【歓迎スキル】
            ・WebAPIの設計と実装経験
            ・TDD（テスト駆動開発）の経験
            """,
            """
            【募集職種】財務アナリスト
            【必要スキル】
            ・財務諸表分析経験
            ・財務モデリングとフォーキャスト経験
            ・Excelの高度な使用経験
            ・ビジネス指標の理解と分析能力
            【歓迎スキル】
            ・会計または財務の資格
            ・ERPシステムの使用経験
            """
        ]
    }
]

# 職種や業界特有のキーワードを定義
important_tech_keywords = [
    "Python", "Java", "JavaScript", "SQL", "Django", "Flask", "React",
    "Git", "Docker", "AWS", "TensorFlow", "機械学習", "データ分析",
    "API", "マイクロサービス", "クラウド", "コンテナ"
]

important_design_keywords = [
    "デザイン", "UI", "UX", "Photoshop", "Illustrator", "XD", "Figma",
    "HTML", "CSS", "レスポンシブ", "ワイヤーフレーム", "プロトタイプ",
    "グラフィック", "ユーザーインターフェース", "ビジュアル"
]

important_marketing_keywords = [
    "マーケティング", "広告", "SNS", "Google Analytics", "SEO", "コンテンツ",
    "KPI", "CRM", "リード", "コンバージョン", "データ分析", "キャンペーン",
    "ブランディング", "デジタルマーケティング", "顧客獲得"
]

# 3. 評価の実行
def run_evaluation(use_weighted_similarity=True):
    evaluator = ResumeJobSimilarityEvaluator()

    # 評価するモデルの定義
    models = {
        "BERT (CLS)": lambda text: evaluator.get_bert_embedding(text, large=False),
        "BERT (Mean Pooling)": lambda text: evaluator.get_bert_mean_pooling(text, large=False),
        "BERT-large (CLS)": lambda text: evaluator.get_bert_embedding(text, large=True),
        "BERT-large (Mean Pooling)": lambda text: evaluator.get_bert_mean_pooling(text, large=True),
        "LUKE-japanese": lambda text: evaluator.get_luke_embedding(text),
        "Sentence-BERT (Multilingual)": lambda text: evaluator.get_sentence_transformer_embedding(text, model_type="multilingual"),
        "Sentence-BERT (Japanese)": lambda text: evaluator.get_sentence_transformer_embedding(text, model_type="japanese"),
        "Sentence-LUKE (Japanese)": lambda text: evaluator.get_sentence_transformer_embedding(text, model_type="japanese_luke"),
    }

    # 重み付き類似度計算用のモデルを追加
    if use_weighted_similarity:
        models.update({
            "Weighted BERT-large (Mean Pooling)": lambda text: evaluator.get_bert_mean_pooling(text, large=True),
            "Weighted Sentence-BERT (Japanese)": lambda text: evaluator.get_sentence_transformer_embedding(text, model_type="japanese"),
        })

    # 結果の保存用辞書
    results = {}
    all_scores = []

    # 各モデルの評価
    for model_name, embedding_func in models.items():
        print(f"\n=== {model_name} の評価 ===")
        model_results = []

        # 各評価データに対して
        for i, data in enumerate(evaluation_dataset):
            resume = data["resume"]
            matching_jobs = data["matching_jobs"]
            non_matching_jobs = data["non_matching_jobs"]

            # キーワードリストを職種に基づいて選択
            if i == 0:  # エンジニア/プログラマー
                keywords = important_tech_keywords
            elif i == 1:  # デザイナー
                keywords = important_design_keywords
            elif i == 2:  # マーケター
                keywords = important_marketing_keywords
            else:
                keywords = None

            # 類似度の計算
            matching_scores = []
            for job in matching_jobs:
                if "Weighted" in model_name and keywords:
                    similarity = evaluator.get_weighted_resume_job_similarity(
                        resume, job, embedding_func, important_keywords=keywords
                    )
                else:
                    similarity = evaluator.get_resume_job_similarity(resume, job, embedding_func)

                matching_scores.append(similarity)
                all_scores.append({
                    "model": model_name,
                    "resume_id": i,
                    "job_type": "matching",
                    "similarity": similarity
                })

            non_matching_scores = []
            for job in non_matching_jobs:
                if "Weighted" in model_name and keywords:
                    similarity = evaluator.get_weighted_resume_job_similarity(
                        resume, job, embedding_func, important_keywords=keywords
                    )
                else:
                    similarity = evaluator.get_resume_job_similarity(resume, job, embedding_func)

                non_matching_scores.append(similarity)
                all_scores.append({
                    "model": model_name,
                    "resume_id": i,
                    "job_type": "non_matching",
                    "similarity": similarity
                })

            # 平均スコアの計算
            avg_matching = np.mean(matching_scores)
            avg_non_matching = np.mean(non_matching_scores)
            separation = avg_matching - avg_non_matching

            model_results.append({
                "resume_id": i,
                "avg_matching": avg_matching,
                "avg_non_matching": avg_non_matching,
                "separation": separation,
                "matching_scores": matching_scores,
                "non_matching_scores": non_matching_scores
            })

        results[model_name] = model_results

    # 4. 結果の出力
    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    output_file = f"resume_job_similarity_evaluation_{timestamp}.txt"

    # 結果のデータフレーム化とビジュアライズ
    df_scores = pd.DataFrame(all_scores)

    # 評価結果の可視化
    visualize_results(df_scores, results, timestamp)

    with open(output_file, "w", encoding="utf-8") as f:
        f.write("職務経歴と求人スキルの類似度評価結果\n")
        f.write("=" * 50 + "\n\n")
        f.write(f"評価日時: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n")

        # モデルごとの集計結果
        f.write("【モデル比較サマリー】\n")
        f.write("-" * 30 + "\n")
        model_summary = []
        for model_name, model_results in results.items():
            avg_separation = np.mean([r["separation"] for r in model_results])
            f.write(f"{model_name}:\n")
            f.write(f"  平均分離度: {avg_separation:.3f}\n")
            model_summary.append({"model": model_name, "avg_separation": avg_separation})
        f.write("\n")

        # モデルのランキング
        model_ranking = sorted(model_summary, key=lambda x: x["avg_separation"], reverse=True)
        f.write("【モデルランキング】\n")
        for i, model_data in enumerate(model_ranking):
            f.write(f"{i+1}. {model_data['model']} (平均分離度: {model_data['avg_separation']:.3f})\n")
        f.write("\n")

        # 詳細な結果
        f.write("【詳細結果】\n")
        f.write("=" * 50 + "\n\n")

        for model_name, model_results in results.items():
            f.write(f"モデル: {model_name}\n")
            f.write("-" * 30 + "\n")

            for result in model_results:
                resume_id = result["resume_id"]
                f.write(f"職務経歴書 {resume_id+1}\n")
                f.write(f"  マッチング求人の平均スコア: {result['avg_matching']:.3f}\n")
                f.write(f"  非マッチング求人の平均スコア: {result['avg_non_matching']:.3f}\n")
                f.write(f"  分離度: {result['separation']:.3f}\n")

                f.write("  マッチング求人の詳細:\n")
                for i, score in enumerate(result['matching_scores']):
                    f.write(f"    - 求人 {i+1}: {score:.3f}\n")

                f.write("  非マッチング求人の詳細:\n")
                for i, score in enumerate(result['non_matching_scores']):
                    f.write(f"    - 求人 {i+1}: {score:.3f}\n")
                f.write("\n")

            f.write("\n" + "=" * 50 + "\n\n")

    print(f"評価結果を {output_file} に保存しました")

    # Google Colabでファイルをダウンロード
    try:
        from google.colab import files
        files.download(output_file)

        # 可視化した画像もダウンロード
        files.download(f"model_comparison_{timestamp}.png")
        files.download(f"model_boxplot_{timestamp}.png")
        files.download(f"detail_comparison_{timestamp}.png")
    except:
        print("注: Google Colab環境ではないため、ファイルのダウンロードはスキップされました。")

def visualize_results(df_scores, results, timestamp):
    """評価結果の可視化"""

    # 1. モデルごとの類似度比較
    plt.figure(figsize=(14, 8))
    sns.barplot(x="model", y="similarity", hue="job_type", data=df_scores)
    plt.title("各モデルにおける類似度比較", fontsize=16)
    plt.xlabel("モデル", fontsize=14)
    plt.ylabel("類似度", fontsize=14)
    plt.xticks(rotation=45, ha='right')
    plt.legend(title="求人タイプ", labels=["マッチング求人", "非マッチング求人"])
    plt.tight_layout()
    plt.savefig(f"model_comparison_{timestamp}.png")

    # 2. モデルごとの分離度（箱ひげ図）
    plt.figure(figsize=(14, 8))
    sns.boxplot(x="model", y="similarity", hue="job_type", data=df_scores)
    plt.title("各モデルにおける類似度分布", fontsize=16)
    plt.xlabel("モデル", fontsize=14)
    plt.ylabel("類似度", fontsize=14)
    plt.xticks(rotation=45, ha='right')
    plt.legend(title="求人タイプ", labels=["マッチング求人", "非マッチング求人"])
    plt.tight_layout()
    plt.savefig(f"model_boxplot_{timestamp}.png")

    # 3. 職務経歴ごとの詳細比較
    # 特定のモデルを選択して詳細比較
    top_models = ["Sentence-BERT (Japanese)", "BERT-large (Mean Pooling)"]
    df_detail = df_scores[df_scores["model"].isin(top_models)]

    plt.figure(figsize=(14, 8))
    g = sns.catplot(
        data=df_detail, kind="bar",
        x="resume_id", y="similarity", hue="job_type", col="model",
        height=6, aspect=1.2, legend=False
    )
    g.set_axis_labels("職務経歴書ID", "類似度")
    g.set_titles("{col_name}")
    plt.legend(title="求人タイプ", labels=["マッチング求人", "非マッチング求人"])
    plt.tight_layout()
    plt.savefig(f"detail_comparison_{timestamp}.png")

    # 4. モデルの平均分離度のランキング
    model_summary = []
    for model_name, model_results in results.items():
        avg_separation = np.mean([r["separation"] for r in model_results])
        model_summary.append({"model": model_name, "avg_separation": avg_separation})

    df_summary = pd.DataFrame(model_summary).sort_values("avg_separation", ascending=False)

    plt.figure(figsize=(12, 8))
    sns.barplot(x="avg_separation", y="model", data=df_summary)
    plt.title("モデル別の平均分離度ランキング", fontsize=16)
    plt.xlabel("平均分離度", fontsize=14)
    plt.ylabel("モデル", fontsize=14)
    plt.tight_layout()
    plt.savefig(f"model_ranking_{timestamp}.png")

# 実行
if __name__ == "__main__":
    run_evaluation()